#!/bin/bash

declare -a files
files+=(AkuAkuTotem AmogusTotem ClearScaffolding EnderTurtle NoPumpkinBlur Plants Sugarcane Unsuspicious)

cd ~/Minecraft
rm -r CypoPack-All/assets
for i in ${files[@]}; do
	cp -r "CypoPack-$i"/assets/* "CypoPack-All/assets"
done

./zazipovavac
