#!/bin/bash

cd ~/Minecraft
declare -a files
files+=(AkuAkuTotem All AmogusTotem ClearScaffolding EnderTurtle NoPumpkinBlur Plants Sugarcane Unsuspicious)

for i in ${files[@]}; do
	cd "./CypoPack-$i"
	#zip "zip/CypoPack-$i".zip "CypoPack-$i"/"*"
	zip "CypoPack-$i".zip *
	mv "CypoPack-$i".zip ../zip
	cd ..
done
